Update path for libirbem.so check in workflow

diff --git a/.github/workflows/apptainer.yml b/.github/workflows/apptainer.yml
--- a/.github/workflows/apptainer.yml
+++ b/.github/workflows/apptainer.yml
@@ -42,7 +42,7 @@ jobs:
 
       - name: Check libirbem.so is present in image
         run: |
-          sudo apptainer exec ${{ env.IMAGE_NAME }}.sif test -f /opt/el_paso/libirbem.so && echo "libirbem.so found" || { echo "libirbem.so NOT found" >&2; exit 1; }
+          sudo apptainer exec ${{ env.IMAGE_NAME }}.sif test -f /opt/el_paso/el_paso/libirbem.so  && echo "libirbem.so found" || { echo "libirbem.so NOT found" >&2; exit 1; }
 
       - name: Test import in image
         run: |
